### ISSUE TITLE
podcast-loader will terminate when no "episodes" parameter is given in conf file (nt)

### ISSUE THREAD

**Issue by fabi3550** [fabi3550/podcast-loader#3]
2020-07-05 15:57:59,846 Started PodcastLoader
2020-07-05 15:57:59,846 call read_config_file
2020-07-05 15:57:59,847 {'target_directory': '/XXX', 'podcasts': [{'podcast': 'Datenkanal', 'url': 'http://static.datenkanal.org/mp3.rss2'}]}
2020-07-05 15:57:59,847 found Datenkanal (http://static.datenkanal.org/mp3.rss2)
Traceback (most recent call last):
  File "podcastloader.py", line 159, in <module>
    podcastloader = PodcastLoader()
  File "podcastloader.py", line 24, in __init__
    rss_feed = self.load_rss_information(podcast["url"], podcast["episodes"])
KeyError: 'episodes'
[fabian@fabian-desktop podcast-loader2]$

**Comment by fabi3550** [comment]
this is fixed now, episodes parameter will be checked for presence. if no episodes parameter is set, all episodes will be loaded. the application will not crah anymore in this situation.
